apiVersion: v1
data:
  CORS_ORIGIN: '*'
  JWT_EXPIRES_IN: 1d
  JWT_SECRET: change-me-super-secret
  MONGO_URI: mongodb://mongo-auth:29017/authdb
  NODE_ENV: development
  PORT: "5001"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: auth-service-auth-service--env-dev
  name: auth-service--env-dev
