apiVersion: v1
data:
  CORS_ORIGIN: '*'
  NODE_ENV: development
  PORT: "5004"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: notification-service-notification-service--env-dev
  name: notification-service--env-dev
