apiVersion: v1
data:
  CORS_ORIGIN: '*'
  INTERNAL_SERVICE_TOKEN: change-me-internal-token
  NODE_ENV: development
  PORT: "5005"
  SUPPORT_SERVICE_URL: http://support-service:5003
  TICKET_SERVICE_URL: http://ticket-service:5002
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: reporting-service-reporting-service--env-dev
  name: reporting-service--env-dev
