apiVersion: v1
data:
  CORS_ORIGIN: '*'
  NODE_ENV: production
  PORT: "7004"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: notification-service-notification-service--env-prod
  name: notification-service--env-prod
