apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: support-service
  name: support-service
spec:
  ports:
    - name: "7003"
      port: 7003
      targetPort: 7003
  selector:
    io.kompose.service: support-service
