apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongo-auth-prod
  name: mongo-auth-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
