services:

  mongo-auth:
    image: mongo:7
    container_name: mongo-auth-test
    ports:
      - "28017:27017"
    volumes:
      - mongo_auth_test:/data/db
    networks:
      - support-net

  mongo-ticket:
    image: mongo:7
    container_name: mongo-ticket-test
    ports:
      - "28018:27017"
    volumes:
      - mongo_ticket_test:/data/db
    networks:
      - support-net

  mongo-support:
    image: mongo:7
    container_name: mongo-support-test
    ports:
      - "28019:27017"
    volumes:
      - mongo_support_test:/data/db
    networks:
      - support-net

  frontend:
    build:
      context: ../frontend
    env_file:
      - ../frontend/.env.test  
    ports:
      - "3001:80"
    environment:
      NODE_ENV: test
    networks:
      - support-net

  auth-service:
    build:
      context: ../auth-service
    env_file:
      - ../auth-service/.env.test
    ports:
      - "6001:5001"
    environment:
      NODE_ENV: test
      MONGO_URI: mongodb://mongo-auth:27017/authdb_test
    depends_on:
      - mongo-auth
    networks:
      - support-net

  ticket-service:
    build:
      context: ../ticket-service
    env_file:
      - ../ticket-service/.env.test
    ports:
      - "6002:5002"
    environment:
      NODE_ENV: test
      MONGO_URI: mongodb://mongo-ticket:27017/ticketdb_test
    depends_on:
      - mongo-ticket
    networks:
      - support-net

  support-service:
    build:
      context: ../support-service
    env_file:
      - ../support-service/.env.test
    ports:
      - "6003:5003"
    environment:
      NODE_ENV: test
    depends_on:
      - mongo-support
      - auth-service
      - ticket-service
      - notification-service
    networks:
      - support-net

  notification-service:
    build:
      context: ../notification-service
    env_file:
      - ../notification-service/.env.test
    ports:
      - "6004:5004"
    environment:
      NODE_ENV: test
    networks:
      - support-net

  reporting-service:
    build:
      context: ../reporting-service
    env_file:
      - ../reporting-service/.env.test
    ports:
      - "6005:5005"
    environment:
      NODE_ENV: test
    depends_on:
      - ticket-service
      - support-service
    networks:
      - support-net

networks:
  support-net:
    driver: bridge

volumes:
  mongo_auth_test:
  mongo_ticket_test:
  mongo_support_test: